<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="armh_handle">

<!-- roslaunch urdf_tutorial display.launch model:=handle.urdf gui:=True -->
<!-- rosrun xacro xacro.py handle_urdf.xacro > handle.urdf -->
<!-- tip: use measurements from solid to find the origins and length -->

<xacro:property name="flex_joint_length" value=".016" />
<xacro:property name="flex_joint_steps" value="9" />
<xacro:property name="proximal_link_length" value=".062" />
<xacro:property name="pi" value="3.14" />


<xacro:macro name="flex_link" params="side finger_id link_id">
  <link name="${side}_finger[${finger_id}]/flexible_link_${link_id}">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
    <collision>
      <geometry>
        <box size=".014 ${(flex_joint_length/flex_joint_steps)*0.99} .006"/>
      </geometry>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
    </collision>
    <visual>
      <geometry>
        <box size=".014 ${(flex_joint_length/flex_joint_steps)*0.99} .006"/>
      </geometry>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <material name="darkgray">
        <color rgba="0.2 0.2 0.2 1"/>
      </material>
    </visual>
  </link>

</xacro:macro>

<xacro:macro name="flex_joint" params="side finger_id link_from link_to">
  <joint name="${side}_finger[${finger_id}]/flexible_joint_flex_from_${link_from}_to_${link_to}" type="revolute">
    <parent link="${side}_finger[${finger_id}]/flexible_link_${link_from}"/>
    <child link="${side}_finger[${finger_id}]/flexible_link_hidden_between_${link_from}_and_${link_to}"/>
    <origin xyz="0 0 ${flex_joint_length/flex_joint_steps}" />
    <axis xyz="-1 0 0"/>
    <limit effort="1000.0" lower="0.0" upper="${pi/2}" velocity="0.5"/>
  </joint>
  <link name="${side}_finger[${finger_id}]/flexible_link_hidden_between_${link_from}_and_${link_to}">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
    <collision>
      <geometry>
        <box size="0 0 0"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    <visual>
      <geometry>
        <box size="0 0 0"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>
  </link>
  <joint name="${side}_finger[${finger_id}]/flexible_joint_twist_from_${link_from}_to_${link_to}" type="revolute">
    <parent link="${side}_finger[${finger_id}]/flexible_link_hidden_between_${link_from}_and_${link_to}"/>
    <child link="${side}_finger[${finger_id}]/flexible_link_${link_to}"/>
    <origin xyz="0 0 0" />
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="0.0" upper="${pi/2}" velocity="0.5"/>
  </joint>
</xacro:macro>

<xacro:macro name="flex_joint_connector" params="side finger_id">

  <!-- make a connection between proximal to flexible-->
  <joint name="${side}_finger[${finger_id}]/flexible_joint_flex_from_proximal_to_1" type="revolute">
    <parent link="${side}_finger[${finger_id}]/proximal_link"/>
    <child link="${side}_finger[${finger_id}]/flexible_link_hidden_between_proximal_link_and_1"/>
    <origin xyz="0 0 ${proximal_link_length}" />
    <axis xyz="-1 0 0"/>
    <limit effort="1000.0" lower="0.0" upper="${pi/2}" velocity="0.5"/>
  </joint>
  <link name="${side}_finger[${finger_id}]/flexible_link_hidden_between_proximal_link_and_1">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
    <collision>
      <geometry>
        <box size="0 0 0"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    <visual>
      <geometry>
        <box size="0 0 0"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>
  </link>
  <joint name="${side}_finger[${finger_id}]/flexible_joint_twist_from_proximal_to_1" type="revolute">
    <parent link="${side}_finger[${finger_id}]/flexible_link_hidden_between_proximal_link_and_1"/>
    <child link="${side}_finger[${finger_id}]/flexible_link_1"/>
    <origin xyz="0 0 0" />
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="0.0" upper="${pi/2}" velocity="0.5"/>
  </joint>


  <!-- make a connection between flexible to distal-->
  <joint name="${side}_finger[${finger_id}]/flexible_joint_flex_from_9_to_distal" type="revolute">
    <parent link="${side}_finger[${finger_id}]/flexible_link_9"/>
    <child link="${side}_finger[${finger_id}]/flexible_link_hidden_between_9_and_distal_link"/>
    <origin xyz="0 0 ${flex_joint_length/flex_joint_steps}" />
    <axis xyz="-1 0 0"/>
    <limit effort="1000.0" lower="0.0" upper="${pi/2}" velocity="0.5"/>
  </joint>
  <link name="${side}_finger[${finger_id}]/flexible_link_hidden_between_9_and_distal_link">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
    <collision>
      <geometry>
        <box size="0 0 0"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    <visual>
      <geometry>
        <box size="0 0 0"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>
  </link>
  <joint name="${side}_finger[${finger_id}]/flexible_joint_twist_from_9_to_distal" type="revolute">
    <parent link="${side}_finger[${finger_id}]/flexible_link_hidden_between_9_and_distal_link"/>
    <child link="${side}_finger[${finger_id}]/distal_link"/>
    <origin xyz="0 0 0" />
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="0.0" upper="${pi/2}" velocity="0.5"/>
  </joint>
</xacro:macro>

<xacro:macro name="irobot_hand" params="side parent reflect *origin">
  <xacro:flex_link side="${side}" finger_id="0" link_id="1"/>
  <xacro:flex_link side="${side}" finger_id="0" link_id="2"/>
  <xacro:flex_link side="${side}" finger_id="0" link_id="3"/>
  <xacro:flex_link side="${side}" finger_id="0" link_id="4"/>
  <xacro:flex_link side="${side}" finger_id="0" link_id="5"/>
  <xacro:flex_link side="${side}" finger_id="0" link_id="6"/>
  <xacro:flex_link side="${side}" finger_id="0" link_id="7"/>
  <xacro:flex_link side="${side}" finger_id="0" link_id="8"/>
  <xacro:flex_link side="${side}" finger_id="0" link_id="9"/>
  <xacro:flex_joint side="${side}" finger_id="0" link_from="1" link_to="2"/>
  <xacro:flex_joint side="${side}" finger_id="0" link_from="2" link_to="3"/>
  <xacro:flex_joint side="${side}" finger_id="0" link_from="3" link_to="4"/>
  <xacro:flex_joint side="${side}" finger_id="0" link_from="4" link_to="5"/>
  <xacro:flex_joint side="${side}" finger_id="0" link_from="5" link_to="6"/>
  <xacro:flex_joint side="${side}" finger_id="0" link_from="6" link_to="7"/>
  <xacro:flex_joint side="${side}" finger_id="0" link_from="7" link_to="8"/>
  <xacro:flex_joint side="${side}" finger_id="0" link_from="8" link_to="9"/>
  <xacro:flex_joint_connector side="${side}" finger_id="0"/>

  <xacro:flex_link side="${side}" finger_id="1" link_id="1"/>
  <xacro:flex_link side="${side}" finger_id="1" link_id="2"/>
  <xacro:flex_link side="${side}" finger_id="1" link_id="3"/>
  <xacro:flex_link side="${side}" finger_id="1" link_id="4"/>
  <xacro:flex_link side="${side}" finger_id="1" link_id="5"/>
  <xacro:flex_link side="${side}" finger_id="1" link_id="6"/>
  <xacro:flex_link side="${side}" finger_id="1" link_id="7"/>
  <xacro:flex_link side="${side}" finger_id="1" link_id="8"/>
  <xacro:flex_link side="${side}" finger_id="1" link_id="9"/>
  <xacro:flex_joint side="${side}" finger_id="1" link_from="1" link_to="2"/>
  <xacro:flex_joint side="${side}" finger_id="1" link_from="2" link_to="3"/>
  <xacro:flex_joint side="${side}" finger_id="1" link_from="3" link_to="4"/>
  <xacro:flex_joint side="${side}" finger_id="1" link_from="4" link_to="5"/>
  <xacro:flex_joint side="${side}" finger_id="1" link_from="5" link_to="6"/>
  <xacro:flex_joint side="${side}" finger_id="1" link_from="6" link_to="7"/>
  <xacro:flex_joint side="${side}" finger_id="1" link_from="7" link_to="8"/>
  <xacro:flex_joint side="${side}" finger_id="1" link_from="8" link_to="9"/>
  <xacro:flex_joint_connector side="${side}" finger_id="1"/>

  <xacro:flex_link side="${side}" finger_id="2" link_id="1"/>
  <xacro:flex_link side="${side}" finger_id="2" link_id="2"/>
  <xacro:flex_link side="${side}" finger_id="2" link_id="3"/>
  <xacro:flex_link side="${side}" finger_id="2" link_id="4"/>
  <xacro:flex_link side="${side}" finger_id="2" link_id="5"/>
  <xacro:flex_link side="${side}" finger_id="2" link_id="6"/>
  <xacro:flex_link side="${side}" finger_id="2" link_id="7"/>
  <xacro:flex_link side="${side}" finger_id="2" link_id="8"/>
  <xacro:flex_link side="${side}" finger_id="2" link_id="9"/>
  <xacro:flex_joint side="${side}" finger_id="2" link_from="1" link_to="2"/>
  <xacro:flex_joint side="${side}" finger_id="2" link_from="2" link_to="3"/>
  <xacro:flex_joint side="${side}" finger_id="2" link_from="3" link_to="4"/>
  <xacro:flex_joint side="${side}" finger_id="2" link_from="4" link_to="5"/>
  <xacro:flex_joint side="${side}" finger_id="2" link_from="5" link_to="6"/>
  <xacro:flex_joint side="${side}" finger_id="2" link_from="6" link_to="7"/>
  <xacro:flex_joint side="${side}" finger_id="2" link_from="7" link_to="8"/>
  <xacro:flex_joint side="${side}" finger_id="2" link_from="8" link_to="9"/>
  <xacro:flex_joint_connector side="${side}" finger_id="2"/>

  <!-- joint to irobot hand -->
  <joint name="${side}_irobot_hand_joint" type="fixed">
    <insert_block name="origin"/>
    <parent link="${parent}"/>
    <child link="${side}_base_link"/>
  </joint>

  <link name="${side}_base_link">
      <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
      </inertial>
    <collision>
      <geometry>
        <mesh filename="package://irobot_hand/meshes/palm.stl"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 -0.038 -0.023"/>
    </collision>
    <visual>
      <geometry>
        <mesh filename="package://irobot_hand/meshes/palm.stl"/>
      </geometry>
      <material name="darkgray">
        <color rgba="0.2 0.2 0.2 1"/>
      </material>
      <origin rpy="0 0 0" xyz="0 -0.038 -0.023"/>
    </visual>
  </link>

  <link name="${side}_finger[0]/base_rotation_link">
      <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
      </inertial>
    <collision>
      <geometry>
        <mesh filename="package://irobot_hand/meshes/finger_base.stl"/>
      </geometry>
      <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
    </collision>
    <visual>
      <geometry>
        <mesh filename="package://irobot_hand/meshes/finger_base.stl"/>
      </geometry>
      <material name="darkgray">
        <color rgba="0.2 0.2 0.2 1"/>
      </material>
      <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
    </visual>
  </link>

  <link name="${side}_finger[0]/proximal_link">
      <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
      </inertial>
    <collision>
      <geometry>
        <mesh filename="package://irobot_hand/meshes/finger_proximal.stl"/>
      </geometry>
      <origin rpy="${pi/2} -${pi/2} 0" xyz="0 0 0"/>
    </collision>
    <visual>
      <geometry>
        <mesh filename="package://irobot_hand/meshes/finger_proximal.stl"/>
      </geometry>
      <material name="green">
        <color rgba="0.1 0.6 0.1 1"/>
      </material>
      <origin rpy="${pi/2} -${pi/2} 0" xyz="0 0 0"/>
    </visual>
  </link>

  <link name="${side}_finger[0]/distal_link">
      <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
      </inertial>
    <collision>
      <geometry>
        <mesh filename="package://irobot_hand/meshes/finger_distal.stl"/>
      </geometry>
      <origin rpy="0 ${pi} 0" xyz="0 0 0"/>
    </collision>
    <visual>
      <geometry>
        <mesh filename="package://irobot_hand/meshes/finger_distal.stl"/>
      </geometry>
      <material name="green">
        <color rgba="0.1 0.6 0.1 1"/>
      </material>
      <origin rpy="0 ${pi} 0" xyz="0 0 0"/>
    </visual>
  </link>

  <link name="${side}_finger[1]/base_rotation_link">
      <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
      </inertial>
    <collision>
      <geometry>
        <mesh filename="package://irobot_hand/meshes/finger_base.stl"/>
      </geometry>
      <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
    </collision>
    <visual>
      <geometry>
        <mesh filename="package://irobot_hand/meshes/finger_base.stl"/>
      </geometry>
      <material name="darkgray">
        <color rgba="0.2 0.2 0.2 1"/>
      </material>
      <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
    </visual>
  </link>

  <link name="${side}_finger[1]/proximal_link">
      <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
      </inertial>
    <collision>
      <geometry>
        <mesh filename="package://irobot_hand/meshes/finger_proximal.stl"/>
      </geometry>
      <origin rpy="${pi/2} -${pi/2} 0" xyz="0 0 0"/>
    </collision>
    <visual>
      <geometry>
        <mesh filename="package://irobot_hand/meshes/finger_proximal.stl"/>
      </geometry>
      <material name="green">
        <color rgba="0.1 0.6 0.1 1"/>
      </material>
      <origin rpy="${pi/2} -${pi/2} 0" xyz="0 0 0"/>
    </visual>
  </link>

  <link name="${side}_finger[1]/distal_link">
      <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
      </inertial>
    <collision>
      <geometry>
        <mesh filename="package://irobot_hand/meshes/finger_distal.stl"/>
      </geometry>
      <origin rpy="0 ${pi} 0" xyz="0 0 0"/>
    </collision>
    <visual>
      <geometry>
        <mesh filename="package://irobot_hand/meshes/finger_distal.stl"/>
      </geometry>
      <material name="green">
        <color rgba="0.1 0.6 0.1 1"/>
      </material>
      <origin rpy="0 ${pi} 0" xyz="0 0 0"/>
    </visual>
  </link>

  <link name="${side}_finger[2]/proximal_link">
      <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
      </inertial>
    <collision>
      <geometry>
        <mesh filename="package://irobot_hand/meshes/finger_proximal.stl"/>
      </geometry>
      <origin rpy="${pi/2} -${pi/2} 0" xyz="0 0 0"/>
    </collision>
    <visual>
      <geometry>
        <mesh filename="package://irobot_hand/meshes/finger_proximal.stl"/>
      </geometry>
      <material name="green">
        <color rgba="0.1 0.6 0.1 1"/>
      </material>
      <origin rpy="${pi/2} -${pi/2} 0" xyz="0 0 0"/>
    </visual>
  </link>

  <link name="${side}_finger[2]/distal_link">
      <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
      </inertial>
    <collision>
      <geometry>
        <mesh filename="package://irobot_hand/meshes/finger_distal.stl"/>
      </geometry>
      <origin rpy="0 ${pi} 0" xyz="0 0 0"/>
    </collision>
    <visual>
      <geometry>
        <mesh filename="package://irobot_hand/meshes/finger_distal.stl"/>
      </geometry>
      <material name="green">
        <color rgba="0.1 0.6 0.1 1"/>
      </material>
      <origin rpy="0 ${pi} 0" xyz="0 0 0"/>
    </visual>
  </link>


  <joint name="${side}_finger[0]/joint_base_rotation" type="revolute">
    <parent link="${side}_base_link"/>
    <child link="${side}_finger[0]/base_rotation_link"/>
    <origin xyz="0.03075 0.038 0.069477" rpy="0 0 0" />
    <axis xyz="0 0 -1"/>
    <limit effort="1000.0" lower="0.0" upper="${pi/2}" velocity="0.5"/>
  </joint>

  <joint name="${side}_finger[0]/joint_base" type="revolute">
    <parent link="${side}_finger[0]/base_rotation_link"/>
    <child link="${side}_finger[0]/proximal_link"/>
    <origin xyz="0 0 0.0135" rpy="${pi/2} 0 -${pi}" />
    <axis xyz="-1 0 0"/>
    <limit effort="1000.0" lower="0.0" upper="${pi/2}" velocity="0.5"/>

  </joint>

  <joint name="${side}_finger[1]/joint_base_rotation" type="revolute">
    <parent link="${side}_base_link"/>
    <child link="${side}_finger[1]/base_rotation_link"/>
    <origin xyz="-0.03075 0.038 0.069477" rpy="0 0 0" />
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="0.0" upper="${pi/2}" velocity="0.5"/>
  </joint>

  <joint name="${side}_finger[1]/joint_base" type="revolute">
    <parent link="${side}_finger[1]/base_rotation_link"/>
    <child link="${side}_finger[1]/proximal_link"/>
    <origin xyz="0 0 0.0135" rpy="${pi/2} 0 -${pi}" />
    <axis xyz="-1 0 0"/>
    <limit effort="1000.0" lower="0.0" upper="${pi/2}" velocity="0.5"/>
  </joint>

  <joint name="${side}_finger[2]/joint_base" type="revolute">
    <parent link="${side}_base_link"/>
    <child link="${side}_finger[2]/proximal_link"/>
    <origin xyz="0 -0.038 0.082755" rpy="${pi/2} 0 0" />
    <axis xyz="-1 0 0"/>
    <limit effort="1000.0" lower="0.0" upper="${pi/2}" velocity="0.5"/>
  </joint>
</xacro:macro>

</robot>
