<robot>


  <property name="M_PI" value="3.1415926535897931" />

  <property name="head_mass"           value="10.0" />
  <property name="neck_mass"           value="1.0" />
  <property name="torso_mass"          value="30.0" />
  <property name="hip_mass"            value="10.0" />
  <property name="thigh_pan_mass"      value="1.0" />
  <property name="thigh_lift_mass"     value="5.0" />
  <property name="calf_mass"           value="2.0" />
  <property name="ankle_mass"          value="1.0" />
  <property name="foot_mass"           value="1.0" />
  <property name="shoulder_mass"       value="1.0" />
  <property name="upper_arm_mass"      value="2.0" />
  <property name="forearm_mass"        value="1.0" />
  <property name="wrist_mass"          value="1.0" />
  <property name="hand_mass"           value="1.0" />

  <property name="head_radius"          value="0.15" />
  <property name="neck_radius"          value="0.15" />
  <property name="neck_length"          value="0.15" />
  <property name="torso_x"              value="0.15" />
  <property name="torso_y"              value="0.15" />
  <property name="torso_z"              value="0.15" />
  <property name="hip_x"                value="0.15" />
  <property name="hip_y"                value="0.15" />
  <property name="hip_z"                value="0.15" />

  <property name="thigh_pan_radius"     value="0.15" />
  <property name="thigh_lift_radius"    value="0.15" />
  <property name="thigh_lift_length"    value="0.15" />
  <property name="calf_radius"          value="0.15" />
  <property name="calf_length"          value="0.15" />
  <property name="ankle_radius"         value="0.15" />
  <property name="foot_x"               value="0.15" />
  <property name="foot_y"               value="0.15" />
  <property name="foot_z"               value="0.15" />

  <property name="shoulder_radius"      value="0.15" />
  <property name="upper_arm_radius"     value="0.15" />
  <property name="upper_arm_length"     value="0.15" />
  <property name="forearm_radius"       value="0.15" />
  <property name="forearm_length"       value="0.15" />
  <property name="wrist_radius"         value="0.15" />
  <property name="hand_x"               value="0.15" />
  <property name="hand_y"               value="0.15" />
  <property name="hand_z"               value="0.15" />

  <link name="world"/>
  <link name="haed">
    <inertial>
      <mass value="${head_mass}" />
      <origin xyz="0 0 0" />
      <inertia  ixx="${head_mass/100}" ixy="0" ixz="0" iyy="${head_mass/100}" iyz="0" izz="${head_mass/100}" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <sphere radius="${head_radius}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <sphere radius="${head_radius}"/>
      </geometry>
    </collision>
  </link>
  <joint name="haed_joint">
    <parent link="world"/>
    <child link="head"/>
  </joint>
  <link name="neck">
    <inertial>
      <mass value="${neck_mass}" />
      <origin xyz="0 0 0" />
      <inertia  ixx="${neck_mass/100}" ixy="0" ixz="0" iyy="${neck_mass/100}" iyz="0" izz="${neck_mass/100}" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${-neck_length/2}" rpy="0 0 0" />
      <geometry>
        <sphere radius="${neck_radius}" length="${neck_length}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${-neck_length/2}" rpy="0 0 0" />
      <geometry>
        <sphere radius="${neck_radius}" length="${neck_length}"/>
      </geometry>
    </collision>
  </link>
  <joint name="neck_joint">
    <parent link="haed"/>
    <child link="neck"/>
  </joint>
  <link name="torso">
    <inertial>
      <mass value="${torso_mass}" />
      <origin xyz="0 0 0" />
      <inertia  ixx="${torso_mass/100}" ixy="0" ixz="0" iyy="${torso_mass/100}" iyz="0" izz="${torso_mass/100}" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${-torso_z/2}" rpy="0 0 0" />
      <geometry>
        <box size="${torso_x} ${torso_y} ${torso_z}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${-torso_z/2}" rpy="0 0 0" />
      <geometry>
        <box size="${torso_x} ${torso_y} ${torso_z}"/>
      </geometry>
    </collision>
  </link>
  <joint name="torso_joint">
    <parent link="neck"/>
    <child link="torso"/>
  </joint>
  <link name="hip">
    <inertial>
      <mass value="${hip_mass}" />
      <origin xyz="0 0 0" />
      <inertia  ixx="${hip_mass/100}" ixy="0" ixz="0" iyy="${hip_mass/100}" iyz="0" izz="${hip_mass/100}" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${-hip_z/2}" rpy="0 0 0" />
      <geometry>
        <box size="${hip_x} ${hip_y} ${hip_z}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${-hip_z/2}" rpy="0 0 0" />
      <geometry>
        <box size="${hip_x} ${hip_y} ${hip_z}"/>
      </geometry>
    </collision>
  </link>
  <joint name="hip_joint">
    <parent link="torso"/>
    <child link="hip"/>
  </joint>

  <link name="l_thigh_pan">
    <inertial>
      <mass value="${thigh_pan_mass}" />
      <origin xyz="0 0 0" />
      <inertia  ixx="${thigh_pan_mass/100}" ixy="0" ixz="0" iyy="${thigh_pan_mass/100}" iyz="0" izz="${thigh_pan_mass/100}" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${-thigh_pan_radius/2}" rpy="0 0 0" />
      <geometry>
        <sphere radius="${thigh_pan_radius}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${-thigh_pan_radius/2}" rpy="0 0 0" />
      <geometry>
        <sphere radius="${thigh_pan_radius}"/>
      </geometry>
    </collision>
  </link>
  <joint name="l_thigh_pan_joint">
    <parent link="hip"/>
    <child link="l_thigh_pan"/>
  </joint>
  <link name="l_thigh_lift">
    <inertial>
      <mass value="${thigh_lift_mass}" />
      <origin xyz="0 0 0" />
      <inertia  ixx="${thigh_lift_mass/100}" ixy="0" ixz="0" iyy="${thigh_lift_mass/100}" iyz="0" izz="${thigh_lift_mass/100}" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${-thigh_lift_length/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${thigh_lift_radius}" length="${thigh_lift_length}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${-thigh_lift_length/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${thigh_lift_radius}" length="${thigh_lift_length}"/>
      </geometry>
    </collision>
  </link>
  <joint name="l_thigh_lift_joint">
    <parent link="l_thighpan"/>
    <child link="l_thigh_lift"/>
  </joint>
  <link name="l_calf">
    <inertial>
      <mass value="${calf_mass}" />
      <origin xyz="0 0 0" />
      <inertia  ixx="${calf_mass/100}" ixy="0" ixz="0" iyy="${calf_mass/100}" iyz="0" izz="${calf_mass/100}" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${-calf_length/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${calf_radius}" length="${calf_length}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${-calf_length/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${calf_radius}" length="${calf_length}"/>
      </geometry>
    </collision>
  </link>
  <joint name="l_calf_joint">
    <parent link="l_thigh_lift"/>
    <child link="l_calf"/>
  </joint>
  <link name="l_ankle">
    <inertial>
      <mass value="${ankle_mass}" />
      <origin xyz="0 0 0" />
      <inertia  ixx="${ankle_mass/100}" ixy="0" ixz="0" iyy="${ankle_mass/100}" iyz="0" izz="${ankle_mass/100}" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${-ankle_radius/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${ankle_radius}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${-ankle_radius/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${ankle_radius}"/>
      </geometry>
    </collision>
  </link>
  <joint name="l_ankle_joint">
    <parent link="l_calf"/>
    <child link="l_ankle"/>
  </joint>
  <link name="l_foot">
    <inertial>
      <mass value="${foot_mass}" />
      <origin xyz="0 0 0" />
      <inertia  ixx="${foot_mass/100}" ixy="0" ixz="0" iyy="${foot_mass/100}" iyz="0" izz="${foot_mass/100}" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${-foot_z/2}" rpy="0 0 0" />
      <geometry>
        <box size="${foot_x} ${foot_y} ${foot_z}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${-foot_z/2}" rpy="0 0 0" />
      <geometry>
        <box size="${foot_x} ${foot_y} ${foot_z}"/>
      </geometry>
    </collision>
  </link>
  <joint name="l_foot_joint">
    <parent link="l_ankle"/>
    <child link="l_foot"/>
  </joint>
  <link name="l_shoulder">
    <inertial>
      <mass value="${shoulder_mass}" />
      <origin xyz="0 0 0" />
      <inertia  ixx="${shoulder_mass/100}" ixy="0" ixz="0" iyy="${shoulder_mass/100}" iyz="0" izz="${shoulder_mass/100}" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${-shoulder_radius/2}" rpy="0 0 0" />
      <geometry>
        <sphere radius="${shoulder_radius}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${-shoulder_radius/2}" rpy="0 0 0" />
      <geometry>
        <sphere radius="${shoulder_radius}"/>
      </geometry>
    </collision>
  </link>
  <joint name="l_shoulder_joint">
    <parent link="l_foot"/>
    <child link="l_shoulder"/>
  </joint>
  <link name="l_upper_arm">
    <inertial>
      <mass value="${upper_arm_mass}" />
      <origin xyz="0 0 0" />
      <inertia  ixx="${upper_arm_mass/100}" ixy="0" ixz="0" iyy="${upper_arm_mass/100}" iyz="0" izz="${upper_arm_mass/100}" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${-upper_arm_length/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${upper_arm_radius}" length="${upper_arm_length}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${-upper_arm_length/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${upper_arm_radius}" length="${upper_arm_length}"/>
      </geometry>
    </collision>
  </link>
  <joint name="l_upper_arm_joint">
    <parent link="l_shoulder"/>
    <child link="l_upper_arm"/>
  </joint>
  <link name="l_forearm">
    <inertial>
      <mass value="${forearm_mass}" />
      <origin xyz="0 0 0" />
      <inertia  ixx="${forearm_mass/100}" ixy="0" ixz="0" iyy="${forearm_mass/100}" iyz="0" izz="${forearm_mass/100}" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${-forearm_length/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${forearm_radius}" length="${forearm_length}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${-forearm_length/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${forearm_radius}" length="${forearm_length}"/>
      </geometry>
    </collision>
  </link>
  <joint name="l_forearm_joint">
    <parent link="l_upper_arm"/>
    <child link="l_forearm"/>
  </joint>
  <link name="l_wrist">
    <inertial>
      <mass value="${wrist_mass}" />
      <origin xyz="0 0 0" />
      <inertia  ixx="${wrist_mass/100}" ixy="0" ixz="0" iyy="${wrist_mass/100}" iyz="0" izz="${wrist_mass/100}" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${-wrist_radius/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${wrist_radius}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${-wrist_radius/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${wrist_radius}"/>
      </geometry>
    </collision>
  </link>
  <joint name="l_wrist_joint">
    <parent link="l_forearm"/>
    <child link="l_wrist"/>
  </joint>
  <link name="l_hand">
    <inertial>
      <mass value="${hand_mass}" />
      <origin xyz="0 0 0" />
      <inertia  ixx="${hand_mass/100}" ixy="0" ixz="0" iyy="${hand_mass/100}" iyz="0" izz="${hand_mass/100}" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${-hand_z/2}" rpy="0 0 0" />
      <geometry>
        <box size="${hand_x} ${hand_y} ${hand_z}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${-hand_z/2}" rpy="0 0 0" />
      <geometry>
        <box size="${hand_x} ${hand_y} ${hand_z}"/>
      </geometry>
    </collision>
  </link>
  <joint name="l_hand_joint">
    <parent link="l_wrist"/>
    <child link="l_hand"/>
  </joint>

  <link name="r_thigh_pan">
    <inertial>
      <mass value="${thigh_pan_mass}" />
      <origin xyz="0 0 0" />
      <inertia  ixx="${thigh_pan_mass/100}" ixy="0" ixz="0" iyy="${thigh_pan_mass/100}" iyz="0" izz="${thigh_pan_mass/100}" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${-thigh_pan_radius/2}" rpy="0 0 0" />
      <geometry>
        <sphere radius="${thigh_pan_radius}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${-thigh_pan_radius/2}" rpy="0 0 0" />
      <geometry>
        <sphere radius="${thigh_pan_radius}"/>
      </geometry>
    </collision>
  </link>
  <joint name="r_thigh_pan_joint">
    <parent link="hip"/>
    <child link="r_thigh_pan"/>
  </joint>
  <link name="r_thigh_lift">
    <inertial>
      <mass value="${thigh_lift_mass}" />
      <origin xyz="0 0 0" />
      <inertia  ixx="${thigh_lift_mass/100}" ixy="0" ixz="0" iyy="${thigh_lift_mass/100}" iyz="0" izz="${thigh_lift_mass/100}" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${-thigh_lift_length/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${thigh_lift_radius}" length="${thigh_lift_length}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${-thigh_lift_length/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${thigh_lift_radius}" length="${thigh_lift_length}"/>
      </geometry>
    </collision>
  </link>
  <joint name="r_thigh_lift_joint">
    <parent link="r_thigh_pan"/>
    <child link="r_thigh_lift"/>
  </joint>
  <link name="r_calf">
    <inertial>
      <mass value="${calf_mass}" />
      <origin xyz="0 0 0" />
      <inertia  ixx="${calf_mass/100}" ixy="0" ixz="0" iyy="${calf_mass/100}" iyz="0" izz="${calf_mass/100}" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${-calf_length/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${calf_radius}" length="${calf_length}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${-calf_length/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${calf_radius}" length="${calf_length}"/>
      </geometry>
    </collision>
  </link>
  <joint name="r_calf_joint">
    <parent link="r_thigh_lift"/>
    <child link="r_calf"/>
  </joint>
  <link name="r_ankle">
    <inertial>
      <mass value="${ankle_mass}" />
      <origin xyz="0 0 0" />
      <inertia  ixx="${ankle_mass/100}" ixy="0" ixz="0" iyy="${ankle_mass/100}" iyz="0" izz="${ankle_mass/100}" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${-ankle_radius/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${ankle_radius}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${-ankle_radius/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${ankle_radius}"/>
      </geometry>
    </collision>
  </link>
  <joint name="r_ankle_joint">
    <parent link="r_calf"/>
    <child link="r_ankle"/>
  </joint>
  <link name="r_foot">
    <inertial>
      <mass value="${foot_mass}" />
      <origin xyz="0 0 0" />
      <inertia  ixx="${foot_mass/100}" ixy="0" ixz="0" iyy="${foot_mass/100}" iyz="0" izz="${foot_mass/100}" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${-foot_z/2}" rpy="0 0 0" />
      <geometry>
        <box size="${foot_x} ${foot_y} ${foot_z}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${-foot_z/2}" rpy="0 0 0" />
      <geometry>
        <box size="${foot_x} ${foot_y} ${foot_z}"/>
      </geometry>
    </collision>
  </link>
  <joint name="r_foot_joint">
    <parent link="r_ankle"/>
    <child link="r_foot"/>
  </joint>
  <link name="r_shoulder">
    <inertial>
      <mass value="${shoulder_mass}" />
      <origin xyz="0 0 0" />
      <inertia  ixx="${shoulder_mass/100}" ixy="0" ixz="0" iyy="${shoulder_mass/100}" iyz="0" izz="${shoulder_mass/100}" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${-shoulder_radius/2}" rpy="0 0 0" />
      <geometry>
        <sphere radius="${shoulder_radius}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${-shoulder_radius/2}" rpy="0 0 0" />
      <geometry>
        <sphere radius="${shoulder_radius}"/>
      </geometry>
    </collision>
  </link>
  <joint name="r_shoulder_joint">
    <parent link="r_foot"/>
    <child link="r_shoulder"/>
  </joint>
  <link name="r_upper_arm">
    <inertial>
      <mass value="${upper_arm_mass}" />
      <origin xyz="0 0 0" />
      <inertia  ixx="${upper_arm_mass/100}" ixy="0" ixz="0" iyy="${upper_arm_mass/100}" iyz="0" izz="${upper_arm_mass/100}" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${-upper_arm_length/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${upper_arm_radius}" length="${upper_arm_length}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${-upper_arm_length/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${upper_arm_radius}" length="${upper_arm_length}"/>
      </geometry>
    </collision>
  </link>
  <joint name="r_upper_arm_joint">
    <parent link="r_shoulder"/>
    <child link="r_upper_arm"/>
  </joint>
  <link name="r_forearm">
    <inertial>
      <mass value="${forearm_mass}" />
      <origin xyz="0 0 0" />
      <inertia  ixx="${forearm_mass/100}" ixy="0" ixz="0" iyy="${forearm_mass/100}" iyz="0" izz="${forearm_mass/100}" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${-forearm_length/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${forearm_radius}" length="${forearm_length}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${-forearm_length/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${forearm_radius}" length="${forearm_length}"/>
      </geometry>
    </collision>
  </link>
  <joint name="r_forearm_joint">
    <parent link="r_upper_arm"/>
    <child link="r_forearm"/>
  </joint>
  <link name="r_wrist">
    <inertial>
      <mass value="${wrist_mass}" />
      <origin xyz="0 0 0" />
      <inertia  ixx="${wrist_mass/100}" ixy="0" ixz="0" iyy="${wrist_mass/100}" iyz="0" izz="${wrist_mass/100}" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${-wrist_radius/2}" rpy="0 0 0" />
      <geometry>
        <sphere radius="${wrist_radius}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${-wrist_radius/2}" rpy="0 0 0" />
      <geometry>
        <sphere radius="${wrist_radius}"/>
      </geometry>
    </collision>
  </link>
  <joint name="r_wrist_joint">
    <parent link="r_forearm"/>
    <child link="r_wrist"/>
  </joint>
  <link name="r_hand">
    <inertial>
      <mass value="${hand_mass}" />
      <origin xyz="0 0 0" />
      <inertia  ixx="${hand_mass/100}" ixy="0" ixz="0" iyy="${hand_mass/100}" iyz="0" izz="${hand_mass/100}" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${-hand_z/2}" rpy="0 0 0" />
      <geometry>
        <box size="${hand_x} ${hand_y} ${hand_z}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${-hand_z/2}" rpy="0 0 0" />
      <geometry>
        <box size="${hand_x} ${hand_y} ${hand_z}"/>
      </geometry>
    </collision>
  </link>
  <joint name="r_hand_joint">
    <parent link="r_wrist"/>
    <child link="r_hand"/>
  </joint>




</robot>
