#!/bin/sh

# First argument should be a fully-qualified path to a .world file
# (e.g., `rospack find drc_robot_utils`/worlds/drc_robot.world)
# or a world that's install in $GAZEBO_RESOURCE_PATH/worlds/drc_robot
gazebo -s libgazebo_ros_api_plugin.so $1
