<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="armh_handle">

<!-- roslaunch urdf_tutorial display.launch model:=handle.urdf gui:=True -->
<!-- rosrun xacro xacro.py handle_urdf.xacro > handle.urdf -->
<!-- tip: use measurements from solid to find the origins and length -->

<xacro:property name="flex_joint_length" value=".016" />
<xacro:property name="flex_joint_steps" value="2" />
<xacro:property name="proximal_link_length" value=".062" />
<xacro:property name="pi" value="3.14" />
<xacro:property name="flex_offset" value="0.003"/> <!--${0.5*flex_joint_length/flex_joint_steps}-->

<xacro:macro name="flex_link" params="side finger_id link_id">
  <link name="${side}_finger[${finger_id}]/flexible_link_${link_id}">
    <inertial>
      <mass value="${0.0029 / (2 * flex_joint_steps + 1)}"/>
      <!-- gazebo -> cad mapping
           x -> y
           y -> z
           z -> x
      -->
      <origin xyz="0 0 0" rpy="${-pi/2} ${-pi/2} 0"/>
      <inertia ixx="8.8101e-8" ixy="0" ixz="0.0"
               iyy="${2.04906e-7 / (2 * flex_joint_steps + 1)}" iyz="0.0"
               izz="${2.65921e-7 / (2 * flex_joint_steps + 1)}"/>
    </inertial>
    <collision>
      <geometry>
        <box size=".014 ${(flex_joint_length/flex_joint_steps)*0.99} .006"/>
      </geometry>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
    </collision>
    <visual>
      <geometry>
        <box size=".014 ${(flex_joint_length/flex_joint_steps)*0.99} .006"/>
      </geometry>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <material name="darkgray">
        <color rgba="0.2 0.2 0.2 1"/>
      </material>
    </visual>
  </link>

</xacro:macro>

<xacro:macro name="flex_joint" params="side finger_id link_from link_to">
  <gazebo reference="${side}_finger[${finger_id}]/flexible_joint_flex_from_${link_from}_to_${link_to}">
    <implicitSpringDamper>1</implicitSpringDamper>
  </gazebo>
  <joint name="${side}_finger[${finger_id}]/flexible_joint_flex_from_${link_from}_to_${link_to}" type="revolute">
    <parent link="${side}_finger[${finger_id}]/flexible_link_${link_from}"/>
    <child link="${side}_finger[${finger_id}]/flexible_link_hidden_between_${link_from}_and_${link_to}"/>
    <origin xyz="0 0 ${flex_joint_length/flex_joint_steps}" />
    <axis xyz="-1 0 0"/>
    <limit effort="1000.0" lower="0.0" upper="${pi/2}" velocity="0.5"/>
  </joint>
  <link name="${side}_finger[${finger_id}]/flexible_link_hidden_between_${link_from}_and_${link_to}">
    <inertial>
      <mass value="${0.0029 / (2 * flex_joint_steps + 1)}"/>
      <!-- gazebo -> cad mapping
           x -> y
           y -> z
           z -> x
      -->
      <origin xyz="0 0 0" rpy="${-pi/2} ${-pi/2} 0"/>
      <inertia ixx="8.8101e-8" ixy="0" ixz="0.0"
               iyy="${2.04906e-7 / (2 * flex_joint_steps + 1)}" iyz="0.0"
               izz="${2.65921e-7 / (2 * flex_joint_steps + 1)}"/>
    </inertial>
    <collision>
      <geometry>
        <box size="0 0 0"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    <visual>
      <geometry>
        <box size="0 0 0"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>
  </link>
  <gazebo reference="${side}_finger[${finger_id}]/flexible_joint_twist_from_${link_from}_to_${link_to}">
    <implicitSpringDamper>1</implicitSpringDamper>
  </gazebo>
  <joint name="${side}_finger[${finger_id}]/flexible_joint_twist_from_${link_from}_to_${link_to}" type="revolute">
    <parent link="${side}_finger[${finger_id}]/flexible_link_hidden_between_${link_from}_and_${link_to}"/>
    <child link="${side}_finger[${finger_id}]/flexible_link_${link_to}"/>
    <origin xyz="0 0 0" />
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="0.0" upper="${pi/2}" velocity="0.5"/>
  </joint>
</xacro:macro>

<xacro:macro name="flex_joint_connector" params="side finger_id">

  <!-- make a connection between proximal to flexible-->
  <gazebo reference="${side}_finger[${finger_id}]/flexible_joint_flex_from_proximal_to_1">
    <implicitSpringDamper>1</implicitSpringDamper>
  </gazebo>
  <joint name="${side}_finger[${finger_id}]/flexible_joint_flex_from_proximal_to_1" type="revolute">
    <parent link="${side}_finger[${finger_id}]/proximal_link"/>
    <child link="${side}_finger[${finger_id}]/flexible_link_hidden_between_proximal_link_and_1"/>
    <origin xyz="0 0 ${proximal_link_length + flex_offset}" />
    <axis xyz="-1 0 0"/>
    <limit effort="1000.0" lower="0.0" upper="${pi/2}" velocity="0.5"/>
  </joint>
  <link name="${side}_finger[${finger_id}]/flexible_link_hidden_between_proximal_link_and_1">
    <inertial>
      <!-- <mass value="${0.0029 / 19}"/> -->
      <mass value="${0.0029 / (2 * flex_joint_steps + 1)}"/>
      <!-- gazebo -> cad mapping
           x -> y
           y -> z
           z -> x
      -->
      <origin xyz="0 0 0" rpy="${-pi/2} ${-pi/2} 0"/>
      <inertia ixx="8.8101e-8" ixy="0" ixz="0.0"
               iyy="${2.04906e-7 / (2 * flex_joint_steps + 1)}" iyz="0.0"
               izz="${2.65921e-7 / (2 * flex_joint_steps + 1)}"/>
    </inertial>
    <collision>
      <geometry>
        <box size="0 0 0"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    <visual>
      <geometry>
        <box size="0 0 0"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>
  </link>
  <gazebo reference="${side}_finger[${finger_id}]/flexible_joint_twist_from_proximal_to_1">
    <implicitSpringDamper>1</implicitSpringDamper>
  </gazebo>
  <joint name="${side}_finger[${finger_id}]/flexible_joint_twist_from_proximal_to_1" type="revolute">
    <parent link="${side}_finger[${finger_id}]/flexible_link_hidden_between_proximal_link_and_1"/>
    <child link="${side}_finger[${finger_id}]/flexible_link_1"/>
    <origin xyz="0 0 0" />
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="0.0" upper="${pi/2}" velocity="0.5"/>
  </joint>


  <!-- make a connection between flexible to distal-->
  <gazebo reference="${side}_finger[${finger_id}]/flexible_joint_flex_from_${flex_joint_steps}_to_distal">
    <implicitSpringDamper>1</implicitSpringDamper>
  </gazebo>
  <joint name="${side}_finger[${finger_id}]/flexible_joint_flex_from_${flex_joint_steps}_to_distal" type="revolute">
    <parent link="${side}_finger[${finger_id}]/flexible_link_${flex_joint_steps}"/>
    <child link="${side}_finger[${finger_id}]/flexible_link_hidden_between_${flex_joint_steps}_and_distal_link"/>
    <origin xyz="0 0 ${flex_joint_length/flex_joint_steps - flex_offset}" />
    <axis xyz="-1 0 0"/>
    <limit effort="1000.0" lower="0.0" upper="${pi/2}" velocity="0.5"/>
  </joint>
  <link name="${side}_finger[${finger_id}]/flexible_link_hidden_between_${flex_joint_steps}_and_distal_link">
    <inertial>
      <mass value="${0.0029 / (2 * flex_joint_steps + 1)}"/>
      <!-- gazebo -> cad mapping
           x -> y
           y -> z
           z -> x
      -->
      <origin xyz="0 0 0" rpy="${-pi/2} ${-pi/2} 0"/>
      <inertia ixx="8.8101e-8" ixy="0" ixz="0.0"
               iyy="${2.04906e-7 / (2 * flex_joint_steps + 1)}" iyz="0.0"
               izz="${2.65921e-7 / (2 * flex_joint_steps + 1)}"/>
    </inertial>
    <collision>
      <geometry>
        <box size="0 0 0"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    <visual>
      <geometry>
        <box size="0 0 0"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>
  </link>
  <gazebo reference="${side}_finger[${finger_id}]/flexible_joint_twist_from_${flex_joint_steps}_to_distal">
    <implicitSpringDamper>1</implicitSpringDamper>
  </gazebo>
  <joint name="${side}_finger[${finger_id}]/flexible_joint_twist_from_${flex_joint_steps}_to_distal" type="revolute">
    <parent link="${side}_finger[${finger_id}]/flexible_link_hidden_between_${flex_joint_steps}_and_distal_link"/>
    <child link="${side}_finger[${finger_id}]/distal_link"/>
    <origin xyz="0 0 0" />
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="0.0" upper="${pi/2}" velocity="0.5"/>
  </joint>
</xacro:macro>

<!-- Simplified collisions for the base_rotation_links on fingers 0 and 1 -->
<xacro:macro name="base_rotation_link_collisions">
      <collision name='collision_1'>
        <origin xyz="0 0 -.0025" rpy="0 0 0"/>
        <geometry>
          <cylinder length="0.0145" radius="0.025"/>
        </geometry>
      </collision>

      <collision name='collision_2'>
        <origin xyz="0 0 -.0104" rpy="0 0 0"/>
        <geometry>
          <cylinder length="0.0145" radius="0.0165"/>
        </geometry>
      </collision>

      <collision name='collision_3'>
        <origin xyz="0 0 .0135" rpy="1.5707 0 1.5707"/>
        <geometry>
          <cylinder length="0.02" radius="0.002"/>
        </geometry>
      </collision>

      <collision name='collision_4'>
        <origin xyz="0.013 0 .0135" rpy="1.5707 0 1.5707"/>
        <geometry>
          <cylinder length="0.008" radius="0.009"/>
        </geometry>
      </collision>

      <collision name='collision_5'>
        <origin xyz="-0.013 0 .0135" rpy="1.5707 0 1.5707"/>
        <geometry>
          <cylinder length="0.008" radius="0.009"/>
        </geometry>
      </collision>
</xacro:macro>

<!-- Simplified collisions for the proximal_link on all fingers -->
<xacro:macro name="proximal_link_collisions">
      <collision name='collision1'>
        <origin xyz="0 0.0028 0.033" rpy="0 0 0"/>
        <geometry>
          <box size="0.018 0.019 0.055"/>
        </geometry>
      </collision>

      <collision name='collision2'>
        <origin xyz="0 0 0" rpy="0 1.5707 0"/>
        <geometry>
          <cylinder radius="0.009" length="0.018"/>
        </geometry>
      </collision>
</xacro:macro>

<!-- Simplified collisions for the distal_link on all fingers -->
<xacro:macro name="distal_link_collisions">
      <collision name='collision'>
        <origin xyz="0 0.0024 0.01476" rpy="3.141590 0.001593
             3.141590"/>
        <geometry>
          <box size="0.0175 0.02011 0.03195"/>
        </geometry>
      </collision>
      <collision name='collision_tip'>
        <origin xyz="0 0.004 0.03" rpy="1.57078 0.001593 1.57078"/>
        <geometry>
          <cylinder radius="0.00848" length="0.0175"/>
        </geometry>
      </collision>

      <collision name='collision_nail'>
        <origin xyz="0 -0.00529 0.032" rpy="1.57078 0.001593 0"/>
        <geometry>
          <cylinder radius="0.00750" length="0.00159"/>
        </geometry>
      </collision>
</xacro:macro>

<xacro:macro name="irobot_hand" params="side parent reflect *origin">
  <xacro:flex_link side="${side}" finger_id="0" link_id="1"/>
  <xacro:flex_link side="${side}" finger_id="0" link_id="2"/>
  <!-- only up to flex_joint_steps
  <xacro:flex_link side="${side}" finger_id="0" link_id="3"/>
  <xacro:flex_link side="${side}" finger_id="0" link_id="4"/>
  <xacro:flex_link side="${side}" finger_id="0" link_id="5"/>
  <xacro:flex_link side="${side}" finger_id="0" link_id="6"/>
  <xacro:flex_link side="${side}" finger_id="0" link_id="7"/>
  <xacro:flex_link side="${side}" finger_id="0" link_id="8"/>
  <xacro:flex_link side="${side}" finger_id="0" link_id="9"/>
  -->
  <xacro:flex_joint side="${side}" finger_id="0" link_from="1" link_to="2"/>
  <!-- only up to flex_joint_steps
  <xacro:flex_joint side="${side}" finger_id="0" link_from="2" link_to="3"/>
  <xacro:flex_joint side="${side}" finger_id="0" link_from="3" link_to="4"/>
  <xacro:flex_joint side="${side}" finger_id="0" link_from="4" link_to="5"/>
  <xacro:flex_joint side="${side}" finger_id="0" link_from="5" link_to="6"/>
  <xacro:flex_joint side="${side}" finger_id="0" link_from="6" link_to="7"/>
  <xacro:flex_joint side="${side}" finger_id="0" link_from="7" link_to="8"/>
  <xacro:flex_joint side="${side}" finger_id="0" link_from="8" link_to="9"/>
  -->
  <xacro:flex_joint_connector side="${side}" finger_id="0" />

  <xacro:flex_link side="${side}" finger_id="1" link_id="1"/>
  <xacro:flex_link side="${side}" finger_id="1" link_id="2"/>
  <!-- only up to flex_joint_steps
  <xacro:flex_link side="${side}" finger_id="1" link_id="3"/>
  <xacro:flex_link side="${side}" finger_id="1" link_id="4"/>
  <xacro:flex_link side="${side}" finger_id="1" link_id="5"/>
  <xacro:flex_link side="${side}" finger_id="1" link_id="6"/>
  <xacro:flex_link side="${side}" finger_id="1" link_id="7"/>
  <xacro:flex_link side="${side}" finger_id="1" link_id="8"/>
  <xacro:flex_link side="${side}" finger_id="1" link_id="9"/>
  -->
  <xacro:flex_joint side="${side}" finger_id="1" link_from="1" link_to="2"/>
  <!-- only up to flex_joint_steps
  <xacro:flex_joint side="${side}" finger_id="1" link_from="2" link_to="3"/>
  <xacro:flex_joint side="${side}" finger_id="1" link_from="3" link_to="4"/>
  <xacro:flex_joint side="${side}" finger_id="1" link_from="4" link_to="5"/>
  <xacro:flex_joint side="${side}" finger_id="1" link_from="5" link_to="6"/>
  <xacro:flex_joint side="${side}" finger_id="1" link_from="6" link_to="7"/>
  <xacro:flex_joint side="${side}" finger_id="1" link_from="7" link_to="8"/>
  <xacro:flex_joint side="${side}" finger_id="1" link_from="8" link_to="9"/>
  -->
  <xacro:flex_joint_connector side="${side}" finger_id="1" />

  <xacro:flex_link side="${side}" finger_id="2" link_id="1"/>
  <xacro:flex_link side="${side}" finger_id="2" link_id="2"/>
  <!-- only up to flex_joint_steps
  <xacro:flex_link side="${side}" finger_id="2" link_id="3"/>
  <xacro:flex_link side="${side}" finger_id="2" link_id="4"/>
  <xacro:flex_link side="${side}" finger_id="2" link_id="5"/>
  <xacro:flex_link side="${side}" finger_id="2" link_id="6"/>
  <xacro:flex_link side="${side}" finger_id="2" link_id="7"/>
  <xacro:flex_link side="${side}" finger_id="2" link_id="8"/>
  <xacro:flex_link side="${side}" finger_id="2" link_id="9"/>
  -->
  <xacro:flex_joint side="${side}" finger_id="2" link_from="1" link_to="2"/>
  <!-- only up to flex_joint_steps
  <xacro:flex_joint side="${side}" finger_id="2" link_from="2" link_to="3"/>
  <xacro:flex_joint side="${side}" finger_id="2" link_from="3" link_to="4"/>
  <xacro:flex_joint side="${side}" finger_id="2" link_from="4" link_to="5"/>
  <xacro:flex_joint side="${side}" finger_id="2" link_from="5" link_to="6"/>
  <xacro:flex_joint side="${side}" finger_id="2" link_from="6" link_to="7"/>
  <xacro:flex_joint side="${side}" finger_id="2" link_from="7" link_to="8"/>
  <xacro:flex_joint side="${side}" finger_id="2" link_from="8" link_to="9"/>
  -->
  <xacro:flex_joint_connector side="${side}" finger_id="2" />

  <!-- joint attaching parent link to irobot hand -->
  <joint name="${side}_irobot_hand_joint" type="fixed">
    <insert_block name="origin"/>
    <parent link="${parent}"/>
    <child link="${side}_base_link"/>
  </joint>

  <link name="${side}_base_link">
      <inertial>
        <!-- needs update -->
        <mass value="1.305"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.00125" ixy="0.0" ixz="0.0" iyy="0.00125" iyz="0.0" izz="0.0002"/>
      </inertial>

    <collision name='collision1'>
      <origin xyz="0 0.02 0.045" rpy="0 0 0"/>
      <geometry>
        <box size="0.114 0.1 0.075"/>
      </geometry>
    </collision>

    <collision name='collision2'>
      <origin xyz="0 -0.02 0.045" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.0448" length="0.075"/>
      </geometry>
    </collision>

    <visual>
      <geometry>
        <mesh filename="package://irobot_hand_description/meshes/palm.stl"/>
      </geometry>
      <material name="darkgray">
        <color rgba="0.2 0.2 0.2 1"/>
      </material>
      <origin rpy="0 0 0" xyz="0 -0.038 -0.023"/>
    </visual>
  </link>

  <link name="${side}_finger[0]/base_rotation_link">
      <inertial>
        <!-- needs update -->
        <mass value="0.05"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.0000125" ixy="0.0" ixz="0.0" iyy="0.0000125" iyz="0.0" izz="0.000002"/>
      </inertial>

    <xacro:base_rotation_link_collisions/>

    <visual>
      <geometry>
        <mesh filename="package://irobot_hand_description/meshes/finger_base.stl"/>
      </geometry>
      <material name="darkgray">
        <color rgba="0.2 0.2 0.2 1"/>
      </material>
      <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
    </visual>
  </link>

  <link name="${side}_finger[0]/proximal_link">
      <inertial>
        <mass value="0.0288"/>
        <!-- gazebo -> cad coordinate mapping
             x -> -y
             y -> -z
             z -> x
        -->
        <origin xyz="-0.002630 0.002396 0.021770" rpy="${pi/2} -${pi/2} 0"/>
        <inertia ixx="2.420689e-6" ixy="-1.449042e-6" ixz="-7.74579e-7" iyy="1.196202e-6" iyz="1.90704e-7" izz="1.2736461e-6"/>
      </inertial>

    <xacro:proximal_link_collisions/>

    <visual>
      <geometry>
        <mesh filename="package://irobot_hand_description/meshes/finger_proximal.stl"/>
      </geometry>
      <material name="green">
        <color rgba="0.1 0.6 0.1 1"/>
      </material>
      <origin rpy="${pi/2} -${pi/2} 0" xyz="0 0 0"/>
    </visual>
  </link>

  <link name="${side}_finger[0]/proximal_accelerometer" />

  <joint name="${side}_finger[0]/proximal_link_to_accelerometer" type="fixed">
    <parent link="${side}_finger[0]/proximal_link"/>
    <child link="${side}_finger[0]/proximal_accelerometer"/>
    <origin rpy="${pi/2} 0 0" xyz="0 0 0.05" />
  </joint>

  <link name="${side}_finger[0]/distal_link">
      <inertial>
        <mass value="0.0133"/>
        <!-- gazebo -> cad mapping
             x -> -x
             y -> y
             z -> -z
        -->
        <origin xyz="-0.000066 -0.003142 0.016633" rpy="0 ${pi} 0" />
        <inertia ixx="1.624140e-6" ixy="5.60e-10" ixz="1.33e-10" iyy="1.717885e-6" iyz="-1.19970e-7" izz="5.60221e-7"/>
      </inertial>

    <xacro:distal_link_collisions/>

    <visual>
      <geometry>
        <mesh filename="package://irobot_hand_description/meshes/finger_distal.stl"/>
      </geometry>
      <material name="green">
        <color rgba="0.1 0.6 0.1 1"/>
      </material>
      <origin rpy="0 ${pi} 0" xyz="0 0 0"/>
    </visual>
  </link>

  <link name="${side}_finger[0]/distal_accelerometer" />

  <joint name="${side}_finger[0]/distal_link_to_accelerometer" type="fixed">
    <parent link="${side}_finger[0]/distal_link"/>
    <child link="${side}_finger[0]/distal_accelerometer"/>
    <origin rpy="${pi/2} 0 0" xyz="0 0 0.02" />
  </joint>

  <link name="${side}_finger[1]/base_rotation_link">
      <inertial>
        <mass value="0.05"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.0000125" ixy="0.0" ixz="0.0" iyy="0.0000125" iyz="0.0" izz="0.000002"/>
      </inertial>

    <xacro:base_rotation_link_collisions/>

    <visual>
      <geometry>
        <mesh filename="package://irobot_hand_description/meshes/finger_base.stl"/>
      </geometry>
      <material name="darkgray">
        <color rgba="0.2 0.2 0.2 1"/>
      </material>
      <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
    </visual>
  </link>

  <link name="${side}_finger[1]/proximal_link">
      <inertial>
        <mass value="0.0288"/>
        <!-- gazebo -> cad coordinate mapping
             x -> -y
             y -> -z
             z -> x
        -->
        <origin xyz="-0.002630 0.002396 0.021770" rpy="${pi/2} -${pi/2} 0"/>
        <inertia ixx="2.420689e-6" ixy="-1.449042e-6" ixz="-7.74579e-7" iyy="1.196202e-6" iyz="1.90704e-7" izz="1.2736461e-6"/>
      </inertial>

    <xacro:proximal_link_collisions/>

    <visual>
      <geometry>
        <mesh filename="package://irobot_hand_description/meshes/finger_proximal.stl"/>
      </geometry>
      <material name="green">
        <color rgba="0.1 0.6 0.1 1"/>
      </material>
      <origin rpy="${pi/2} -${pi/2} 0" xyz="0 0 0"/>
    </visual>
  </link>

  <link name="${side}_finger[1]/proximal_accelerometer" />

  <joint name="${side}_finger[1]/proximal_link_to_accelerometer" type="fixed">
    <parent link="${side}_finger[1]/proximal_link"/>
    <child link="${side}_finger[1]/proximal_accelerometer"/>
    <origin rpy="${pi/2} 0 0" xyz="0 0 0.05" />
  </joint>

  <link name="${side}_finger[1]/distal_link">
      <inertial>
        <mass value="0.0133"/>
        <!-- gazebo -> cad mapping
             x -> -x
             y -> y
             z -> -z
        -->
        <origin xyz="-0.000066 -0.003142 0.016633" rpy="0 ${pi} 0" />
        <inertia ixx="1.624140e-6" ixy="5.60e-10" ixz="1.33e-10" iyy="1.717885e-6" iyz="-1.19970e-7" izz="5.60221e-7"/>
      </inertial>

    <xacro:distal_link_collisions/>

    <visual>
      <geometry>
        <mesh filename="package://irobot_hand_description/meshes/finger_distal.stl"/>
      </geometry>
      <material name="green">
        <color rgba="0.1 0.6 0.1 1"/>
      </material>
      <origin rpy="0 ${pi} 0" xyz="0 0 0"/>
    </visual>
  </link>

  <link name="${side}_finger[1]/distal_accelerometer" />

  <joint name="${side}_finger[1]/distal_link_to_accelerometer" type="fixed">
    <parent link="${side}_finger[1]/distal_link"/>
    <child link="${side}_finger[1]/distal_accelerometer"/>
    <origin rpy="${pi/2} 0 0" xyz="0 0 0.02" />
  </joint>

  <link name="${side}_finger[2]/proximal_link">
      <inertial>
        <mass value="0.0288"/>
        <!-- gazebo -> cad coordinate mapping
             x -> -y
             y -> -z
             z -> x
        -->
        <origin xyz="-0.002630 0.002396 0.021770" rpy="${pi/2} -${pi/2} 0"/>
        <inertia ixx="2.420689e-6" ixy="-1.449042e-6" ixz="-7.74579e-7" iyy="1.196202e-6" iyz="1.90704e-7" izz="1.2736461e-6"/>
      </inertial>

    <xacro:proximal_link_collisions/>

    <visual>
      <geometry>
        <mesh filename="package://irobot_hand_description/meshes/finger_proximal.stl"/>
      </geometry>
      <material name="green">
        <color rgba="0.1 0.6 0.1 1"/>
      </material>
      <origin rpy="${pi/2} -${pi/2} 0" xyz="0 0 0"/>
    </visual>
  </link>

  <link name="${side}_finger[2]/proximal_accelerometer" />

  <joint name="${side}_finger[2]/proximal_link_to_accelerometer" type="fixed">
    <parent link="${side}_finger[2]/proximal_link"/>
    <child link="${side}_finger[2]/proximal_accelerometer"/>
    <origin rpy="${pi/2} 0 0" xyz="0 0 0.05" />
  </joint>

  <link name="${side}_finger[2]/distal_link">
      <inertial>
        <mass value="0.0133"/>
        <!-- gazebo -> cad mapping
             x -> -x
             y -> y
             z -> -z
        -->
        <origin xyz="-0.000066 -0.003142 0.016633" rpy="0 ${pi} 0" />
        <inertia ixx="1.624140e-6" ixy="5.60e-10" ixz="1.33e-10" iyy="1.717885e-6" iyz="-1.19970e-7" izz="5.60221e-7"/>
      </inertial>

    <xacro:distal_link_collisions/>

    <visual>
      <geometry>
        <mesh filename="package://irobot_hand_description/meshes/finger_distal.stl"/>
      </geometry>
      <material name="green">
        <color rgba="0.1 0.6 0.1 1"/>
      </material>
      <origin rpy="0 ${pi} 0" xyz="0 0 0"/>
    </visual>
  </link>

  <link name="${side}_finger[2]/distal_accelerometer" />

  <joint name="${side}_finger[2]/distal_link_to_accelerometer" type="fixed">
    <parent link="${side}_finger[2]/distal_link"/>
    <child link="${side}_finger[2]/distal_accelerometer"/>
    <origin rpy="${pi/2} 0 0" xyz="0 0 0.02" />
  </joint>

  <gazebo reference="${side}_finger[0]/joint_base_rotation">
    <implicitSpringDamper>1</implicitSpringDamper>
  </gazebo>
  <joint name="${side}_finger[0]/joint_base_rotation" type="revolute">
    <parent link="${side}_base_link"/>
    <child link="${side}_finger[0]/base_rotation_link"/>
    <origin xyz="0.03075 0.038 0.069477" rpy="0 0 0" />
    <axis xyz="0 0 -1"/>
    <limit effort="1000.0" lower="0.0" upper="${pi/2}" velocity="0.5"/>
  </joint>

  <gazebo reference="${side}_finger[0]/joint_base">
    <implicitSpringDamper>1</implicitSpringDamper>
  </gazebo>
  <joint name="${side}_finger[0]/joint_base" type="revolute">
    <parent link="${side}_finger[0]/base_rotation_link"/>
    <child link="${side}_finger[0]/proximal_link"/>
    <origin xyz="0 0 0.0135" rpy="${pi/2} 0 -${pi}" />
    <axis xyz="-1 0 0"/>
    <limit effort="1000.0" lower="0.0" upper="${7*pi/8}" velocity="0.5"/>

  </joint>
  <gazebo reference="${side}_finger[1]/joint_base_rotation">
    <implicitSpringDamper>1</implicitSpringDamper>
  </gazebo>

  <joint name="${side}_finger[1]/joint_base_rotation" type="revolute">
    <parent link="${side}_base_link"/>
    <child link="${side}_finger[1]/base_rotation_link"/>
    <origin xyz="-0.03075 0.038 0.069477" rpy="0 0 0" />
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="0.0" upper="${pi/2}" velocity="0.5"/>
  </joint>

  <gazebo>
    <joint name="${side}_spread_gearbox" type="gearbox">
      <parent>${side}_finger[0]/base_rotation_link</parent>
      <child>${side}_finger[1]/base_rotation_link</child>
      <!-- ${side}_base_link got lumped into ${parent},
           so we need to fix parser_urdf.cc to propagate name
           changes into this extension before switching this
           to use ${side_base_link}. -->
      <gearbox_reference_body>${parent}</gearbox_reference_body>
      <gearbox_ratio>1.0</gearbox_ratio>
      <axis>
        <!-- yikes, what coordinate frame is this specified in?
             0 0 1 causes NaNs. 0 1 0 works, but unsure why yet.-->
        <xyz>0 1 0</xyz>
      </axis>
      <axis2>
        <!-- yikes, what coordinate frame is this specified in?
             0 0 1 causes NaNs. 0 1 0 works, but unsure why yet.-->
        <xyz>0 1 0</xyz>
      </axis2>
    </joint>
  </gazebo>

  <gazebo reference="${side}_finger[1]/joint_base">
    <implicitSpringDamper>1</implicitSpringDamper>
  </gazebo>
  <joint name="${side}_finger[1]/joint_base" type="revolute">
    <parent link="${side}_finger[1]/base_rotation_link"/>
    <child link="${side}_finger[1]/proximal_link"/>
    <origin xyz="0 0 0.0135" rpy="${pi/2} 0 -${pi}" />
    <axis xyz="-1 0 0"/>
    <limit effort="1000.0" lower="0.0" upper="${7*pi/8}" velocity="0.5"/>
  </joint>

  <gazebo reference="${side}_finger[2]/joint_base">
    <implicitSpringDamper>1</implicitSpringDamper>
  </gazebo>
  <joint name="${side}_finger[2]/joint_base" type="revolute">
    <parent link="${side}_base_link"/>
    <child link="${side}_finger[2]/proximal_link"/>
    <origin xyz="0 -0.038 0.082755" rpy="${pi/2} 0 0" />
    <axis xyz="-1 0 0"/>
    <limit effort="1000.0" lower="0.0" upper="${7*pi/8}" velocity="0.5"/>
  </joint>
</xacro:macro>

</robot>
