#!/usr/bin/env python

from __future__ import print_function
import unittest
import rostest
import subprocess
import sys
import time
import re
import rospy

class ScoringTester(unittest.TestCase):

if __name__ == '__main__':
    rospy.init_node('scoring_checker', anonymous=True)
    rostest.run('drcsim_gazebo', 'scoring_check', ScoringTester, sys.argv)
