<?xml version="1.0"?>
<gazebo xmlns:xacro="http://ros.org/wiki/xacro" version='1.0'>

  <!-- generate a building by using xacro (see http://ros.org/wiki/xacro) -->
  <!-- to generate .model file, run: -->
  <!-- rosrun xacro xacro.py building.model.xacro > building.model -->

  <xacro:macro name="door" params="name height *origin">
    <link name='wall_0' gravity='0' self_collide='0' kinematic='0'>
      <origin pose='0.000000 0.000000 0.000000 0.000000 -0.000000 0.000000'/>
      <inertial mass='10.000000' density='1.000000'>
        <origin pose='0.000000 0.000000 0.000000 0.000000 -0.000000 0.000000'/>
        <inertia ixx='0.100000' ixy='0.000000' ixz='0.000000' iyy='0.100000' iyz='0.000000' izz='0.100000'/>
      </inertial>
      <collision name='wall_0_geom' laser_retro='0.000000'>
        <origin pose='0.000000 0.000000 0.125000 0.000000 -0.000000 0.000000'/>
        <geometry>
          <box size='0.100000 0.500000 0.250000'/>
        </geometry>
        <surface>
          <friction>
            <ode mu='-1.000000' mu2='-1.000000' fdir1='0.000000 0.000000 0.000000' slip1='0.000000' slip2='0.000000'/>
          </friction>
          <bounce restitution_coefficient='0.000000' threshold='100000.000000'/>
          <contact>
            <ode soft_cfm='0.000000' soft_erp='0.200000' kp='1000000000000.000000' kd='1.000000' max_vel='0.000000' min_depth='0.001000'/>
          </contact>
        </surface>
      </collision>
      <visual name='wall_0_geom_visual' cast_shadows='1' laser_retro='0.000000' transparency='0.000000'>
        <origin pose='0.000000 0.000000 0.125000 0.000000 -0.000000 0.000000'/>
        <geometry>
          <box size='0.100000 0.500000 0.250000'/>
        </geometry>
      </visual>
    </link>

    <link name='wall_1' gravity='0' self_collide='0' kinematic='0'>
      <origin pose='10.000000 0.000000 0.000000 0.000000 -0.000000 0.000000'/>
      <inertial mass='10.000000' density='1.000000'>
        <origin pose='0.000000 0.000000 0.000000 0.000000 -0.000000 0.000000'/>
        <inertia ixx='0.100000' ixy='0.000000' ixz='0.000000' iyy='0.100000' iyz='0.000000' izz='0.100000'/>
      </inertial>
      <collision name='wall_1_geom' laser_retro='0.000000'>
        <origin pose='0.000000 0.000000 0.125000 0.000000 -0.000000 0.000000'/>
        <geometry>
          <box size='0.100000 0.500000 0.250000'/>
        </geometry>
        <surface>
          <friction>
            <ode mu='-1.000000' mu2='-1.000000' fdir1='0.000000 0.000000 0.000000' slip1='0.000000' slip2='0.000000'/>
          </friction>
          <bounce restitution_coefficient='0.000000' threshold='100000.000000'/>
          <contact>
            <ode soft_cfm='0.000000' soft_erp='0.200000' kp='1000000000000.000000' kd='1.000000' max_vel='0.000000' min_depth='0.001000'/>
          </contact>
        </surface>
      </collision>
      <visual name='wall_1_geom_visual' cast_shadows='1' laser_retro='0.000000' transparency='0.000000'>
        <origin pose='0.000000 0.000000 0.125000 0.000000 -0.000000 0.000000'/>
        <geometry>
          <box size='0.100000 0.500000 0.250000'/>
        </geometry>
      </visual>
    </link>

    <joint name='wall_1_joint' type='revolute'>
      <origin pose='0.000000 0.000000 0.000000 0.000000 -0.000000 0.000000'/>
      <parent link='wall_0'/>
      <child link='wall_1'/>
      <axis xyz='0.000000 0.000000 1.000000'>
        <dynamics damping='0.000000' friction='0.000000'/>
        <limit lower='-1.570000' upper='1.570000' effort='0.000000' velocity='0.000000'/>
      </axis>
    </joint>
  </xacro:macro>

  <property name="door_height" value="2.0"/>
  <property name="door_width" value="1.0"/>
  <property name="door_x" value="1.0"/>

  <xacro:macro name="front_wall_with_door" params="name depth width height">

    <collision name='${name}_front_top_collision' laser_retro='0.000000'>
      <origin pose='-${(wall_thickness/2)} 0.0 ${(height-door_height)/2+door_height} 0.000000 -0.000000 0.000000'/>
      <geometry>
        <box size='${wall_thickness} ${width} ${height-door_height}'/>
      </geometry>
      <surface>
        <friction>
          <ode mu='-1.000000' mu2='-1.000000' fdir1='0.000000 0.000000 0.000000' slip1='0.000000' slip2='0.000000'/>
        </friction>
        <bounce restitution_coefficient='0.000000' threshold='100000.000000'/>
        <contact>
          <ode soft_cfm='0.000000' soft_erp='0.200000' kp='1000000000000.000000' kd='1.000000' max_vel='0.000000' min_depth='0.001000'/>
        </contact>
      </surface>
    </collision>
    <visual name='${name}_front_top_visual' cast_shadows='1' laser_retro='0.000000' transparency='0.000000'>
      <origin pose='-${(wall_thickness/2)} 0.0 ${(height-door_height)/2+door_height} 0.000000 -0.000000 0.000000'/>
      <geometry>
        <box size='${wall_thickness} ${width} ${height-door_height}'/>
      </geometry>
    </visual>
    
    <collision name='${name}_front_left_collision' laser_retro='0.000000'>
      <origin pose='-${(wall_thickness/2)} ${door_width/2 + (width-door_width)/4} ${door_height/2} 0.000000 -0.000000 0.000000'/>
      <geometry>
        <box size='${wall_thickness} ${(width-door_width)/2} ${door_height}'/>
      </geometry>
      <surface>
        <friction>
          <ode mu='-1.000000' mu2='-1.000000' fdir1='0.000000 0.000000 0.000000' slip1='0.000000' slip2='0.000000'/>
        </friction>
        <bounce restitution_coefficient='0.000000' threshold='100000.000000'/>
        <contact>
          <ode soft_cfm='0.000000' soft_erp='0.200000' kp='1000000000000.000000' kd='1.000000' max_vel='0.000000' min_depth='0.001000'/>
        </contact>
      </surface>
    </collision>
    <visual name='${name}_front_left_visual' cast_shadows='1' laser_retro='0.000000' transparency='0.000000'>
      <origin pose='-${(wall_thickness/2)} ${door_width/2 + (width-door_width)/4} ${door_height/2} 0.000000 -0.000000 0.000000'/>
      <geometry>
        <box size='${wall_thickness} ${(width-door_width)/2} ${door_height}'/>
      </geometry>
    </visual>
    
    <collision name='${name}_front_right_collision' laser_retro='0.000000'>
      <origin pose='-${(wall_thickness/2)} -${door_width/2 + (width-door_width)/4} ${door_height/2} 0.000000 -0.000000 0.000000'/>
      <geometry>
        <box size='${wall_thickness} ${(width-door_width)/2} ${door_height}'/>
      </geometry>
      <surface>
        <friction>
          <ode mu='-1.000000' mu2='-1.000000' fdir1='0.000000 0.000000 0.000000' slip1='0.000000' slip2='0.000000'/>
        </friction>
        <bounce restitution_coefficient='0.000000' threshold='100000.000000'/>
        <contact>
          <ode soft_cfm='0.000000' soft_erp='0.200000' kp='1000000000000.000000' kd='1.000000' max_vel='0.000000' min_depth='0.001000'/>
        </contact>
      </surface>
    </collision>
    <visual name='${name}_front_right_visual' cast_shadows='1' laser_retro='0.000000' transparency='0.000000'>
      <origin pose='-${(wall_thickness/2)} -${door_width/2 + (width-door_width)/4} ${door_height/2} 0.000000 -0.000000 0.000000'/>
      <geometry>
        <box size='${wall_thickness} ${(width-door_width)/2} ${door_height}'/>
      </geometry>
    </visual>
    
  </xacro:macro>

  <property name="wall_thickness" value="0.2"/>

  <xacro:macro name="outer_walls_no_front" params="name width height depth">

    <!-- build with viewer facing the front of the building, x-forward, z-up -->

    <collision name='${name}_right_collision' laser_retro='0.000000'>
      <origin pose='${(depth-wall_thickness)/2} ${-(width-wall_thickness)/2} ${height/2} 0.000000 -0.000000 0.000000'/>
      <geometry>
        <box size='${depth} ${wall_thickness} ${height}'/>
      </geometry>
      <surface>
        <friction>
          <ode mu='-1.000000' mu2='-1.000000' fdir1='0.000000 0.000000 0.000000' slip1='0.000000' slip2='0.000000'/>
        </friction>
        <bounce restitution_coefficient='0.000000' threshold='100000.000000'/>
        <contact>
          <ode soft_cfm='0.000000' soft_erp='0.200000' kp='1000000000000.000000' kd='1.000000' max_vel='0.000000' min_depth='0.001000'/>
        </contact>
      </surface>
    </collision>
    <visual name='${name}_right_visual' cast_shadows='1' laser_retro='0.000000' transparency='0.000000'>
      <origin pose='${(depth-wall_thickness)/2} ${-(width-wall_thickness)/2} ${height/2} 0.000000 -0.000000 0.000000'/>
      <geometry>
        <box size='${depth} ${wall_thickness} ${height}'/>
      </geometry>
    </visual>
    
    <collision name='${name}_left_collision' laser_retro='0.000000'>
      <origin pose='${(depth-wall_thickness)/2} ${(width-wall_thickness)/2} ${height/2} 0.000000 -0.000000 0.000000'/>
      <geometry>
        <box size='${depth} ${wall_thickness} ${height}'/>
      </geometry>
      <surface>
        <friction>
          <ode mu='-1.000000' mu2='-1.000000' fdir1='0.000000 0.000000 0.000000' slip1='0.000000' slip2='0.000000'/>
        </friction>
        <bounce restitution_coefficient='0.000000' threshold='100000.000000'/>
        <contact>
          <ode soft_cfm='0.000000' soft_erp='0.200000' kp='1000000000000.000000' kd='1.000000' max_vel='0.000000' min_depth='0.001000'/>
        </contact>
      </surface>
    </collision>
    <visual name='${name}_left_visual' cast_shadows='1' laser_retro='0.000000' transparency='0.000000'>
      <origin pose='${(depth-wall_thickness)/2} ${(width-wall_thickness)/2} ${height/2} 0.000000 -0.000000 0.000000'/>
      <geometry>
        <box size='${depth} ${wall_thickness} ${height}'/>
      </geometry>
    </visual>
    
    <collision name='${name}_back_collision' laser_retro='0.000000'>
      <origin pose='${(depth-wall_thickness)} 0.0 ${height/2} 0.000000 -0.000000 0.000000'/>
      <geometry>
        <box size='${wall_thickness} ${width} ${height}'/>
      </geometry>
      <surface>
        <friction>
          <ode mu='-1.000000' mu2='-1.000000' fdir1='0.000000 0.000000 0.000000' slip1='0.000000' slip2='0.000000'/>
        </friction>
        <bounce restitution_coefficient='0.000000' threshold='100000.000000'/>
        <contact>
          <ode soft_cfm='0.000000' soft_erp='0.200000' kp='1000000000000.000000' kd='1.000000' max_vel='0.000000' min_depth='0.001000'/>
        </contact>
      </surface>
    </collision>
    <visual name='${name}_back_visual' cast_shadows='1' laser_retro='0.000000' transparency='0.000000'>
      <origin pose='${(depth-wall_thickness)} 0.0 ${height/2} 0.000000 -0.000000 0.000000'/>
      <geometry>
        <box size='${wall_thickness} ${width} ${height}'/>
      </geometry>
    </visual>
<!--
    <collision name='${name}_top_collision' laser_retro='0.000000'>
      <origin pose='${(depth-wall_thickness)/2} 0.0 ${height-wall_thickness/2} 0.000000 -0.000000 0.000000'/>
      <geometry>
        <box size='${depth} ${width} ${wall_thickness}'/>
      </geometry>
      <surface>
        <friction>
          <ode mu='-1.000000' mu2='-1.000000' fdir1='0.000000 0.000000 0.000000' slip1='0.000000' slip2='0.000000'/>
        </friction>
        <bounce restitution_coefficient='0.000000' threshold='100000.000000'/>
        <contact>
          <ode soft_cfm='0.000000' soft_erp='0.200000' kp='1000000000000.000000' kd='1.000000' max_vel='0.000000' min_depth='0.001000'/>
        </contact>
      </surface>
    </collision>
    <visual name='${name}_top_visual' cast_shadows='1' laser_retro='0.000000' transparency='0.000000'>
      <origin pose='${(depth-wall_thickness)/2} 0.0 ${height-wall_thickness/2} 0.000000 -0.000000 0.000000'/>
      <geometry>
        <box size='${depth} ${width} ${wall_thickness}'/>
      </geometry>
    </visual>
-->

    <collision name='${name}_mid_collision' laser_retro='0.000000'>
      <origin pose='${(depth-wall_thickness)/2} ${width/4} ${height/2} 0.000000 -0.000000 0.000000'/>
      <geometry>
        <box size='${depth} ${width/2} ${wall_thickness}'/>
      </geometry>
      <surface>
        <friction>
          <ode mu='-1.000000' mu2='-1.000000' fdir1='0.000000 0.000000 0.000000' slip1='0.000000' slip2='0.000000'/>
        </friction>
        <bounce restitution_coefficient='0.000000' threshold='100000.000000'/>
        <contact>
          <ode soft_cfm='0.000000' soft_erp='0.200000' kp='1000000000000.000000' kd='1.000000' max_vel='0.000000' min_depth='0.001000'/>
        </contact>
      </surface>
    </collision>
    <visual name='${name}_mid_visual' cast_shadows='1' laser_retro='0.000000' transparency='0.000000'>
      <origin pose='${(depth-wall_thickness)/2} ${width/4} ${height/2} 0.000000 -0.000000 0.000000'/>
      <geometry>
        <box size='${depth} ${width/2} ${wall_thickness}'/>
      </geometry>
    </visual>
    
    
  </xacro:macro>

  <xacro:macro name="building" params="name width height depth *origin">
    <!-- origin is the center base of the building -->
    <link name='${name}' gravity='0' self_collide='0' kinematic='0'>
      <insert_block name="origin"/>
      <inertial mass='10.000000' density='1.000000'>
        <origin pose='0.000000 0.000000 0.000000 0.000000 -0.000000 0.000000'/>
        <inertia ixx='0.100000' ixy='0.000000' ixz='0.000000' iyy='0.100000' iyz='0.000000' izz='0.100000'/>
      </inertial>
      <xacro:outer_walls_no_front name="outer_walls_no_front" width="${width}" height="${height}" depth="${depth}"/>
      <xacro:front_wall_with_door name="front_wall_with_door" width="${width}" height="${height}" depth="${depth}"/>
    </link>
  </xacro:macro>


  <model name='building' static='1'>

    <origin pose='0.000000 0.000000 0.0 0.000000 0.000000 0.000000'/>

    <xacro:building name="building_0" width="10.0" depth="20.0" height="8.0">
      <origin pose='0.000000 0.000000 0.000000 0.000000 -0.000000 0.000000'/>
    </xacro:building>

    <plugin filename="libmodify_building.so" name="modify_building"/>
  </model>
</gazebo>
